<article data-product-image-card="{{ $image->id }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-white">
    <div class="relative grid aspect-[4/3] place-items-center bg-slate-100">
        @if ($productImageService->exists($image))<img src="{{ $productImageService->url($image) }}" alt="{{ $image->alt_text ?? '' }}" class="h-full w-full object-cover">@else<span class="text-sm font-semibold text-slate-400">{{ __('admin.product_images.missing_file') }}</span>@endif
        @if ($image->is_main)<span data-main-badge class="absolute left-3 top-3 rounded-full bg-indigo-600 px-3 py-1 text-xs font-bold text-white">{{ __('admin.product_images.main') }}</span>@endif
        <span @class(['absolute right-3 top-3 rounded-full px-3 py-1 text-xs font-bold', 'bg-emerald-100 text-emerald-700' => $image->status, 'bg-slate-200 text-slate-600' => ! $image->status])>{{ $image->status ? __('admin.common.active') : __('admin.common.inactive') }}</span>
    </div>
    <form method="POST" action="{{ route('admin.product-images.update', $image) }}" class="space-y-3 p-4">@csrf @method('PUT')
        <div><label class="text-xs font-bold text-slate-600">{{ __('admin.product_images.alt_text') }}</label><input name="alt_text" maxlength="255" value="{{ $image->alt_text }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div><label class="text-xs font-bold text-slate-600">{{ __('admin.product_images.sort_order') }}</label><input name="sort_order" type="number" min="0" value="{{ $image->sort_order }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div class="flex items-center justify-between gap-3"><label class="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name="status" type="checkbox" value="1" @checked($image->status) class="h-5 w-5 rounded border-slate-300 text-indigo-600">{{ __('admin.common.active') }}</label><label class="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name="is_main" type="checkbox" value="1" @checked($image->is_main) class="h-5 w-5 rounded border-slate-300 text-indigo-600">{{ __('admin.product_images.main') }}</label></div>
        <button class="w-full rounded-lg border border-indigo-200 px-3 py-2 text-sm font-bold text-indigo-700 hover:bg-indigo-50">{{ __('admin.common.save') }}</button>
    </form>
    <form id="product-image-delete-{{ $image->id }}" method="POST" action="{{ route('admin.product-images.destroy', $image) }}" class="hidden">@csrf @method('DELETE')</form>
    <div class="flex items-center justify-between gap-2 border-t border-slate-200 p-4"><form method="POST" action="{{ route('admin.product-images.set-main', $image) }}">@csrf @method('PUT')<button @disabled($image->is_main || ! $image->status) class="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-700 disabled:cursor-not-allowed disabled:opacity-40">{{ __('admin.product_images.set_main') }}</button></form><details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">{{ __('admin.product_tabs.more') }}</summary><div class="absolute bottom-full right-0 z-10 mb-1 w-28 rounded-lg border bg-white p-1 shadow-xl"><button type="submit" form="product-image-delete-{{ $image->id }}" onclick="return confirm(@js(__('admin.product_images.delete_confirm')))" class="w-full rounded-md px-2 py-2 text-left text-xs font-bold text-rose-700 hover:bg-rose-50">{{ __('admin.common.delete') }}</button></div></details></div>
</article>
