<div data-option-value-row="{{ $value->id }}">
    <form method="POST" action="{{ route('admin.product-option-values.update', $value) }}" data-async-save class="grid items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-[1fr_1fr_130px_90px_auto_auto]">
        @csrf @method('PUT')
        <input name="value" value="{{ $value->value }}" maxlength="100" required class="rounded-lg border-slate-300 text-sm">
        <input name="display_value" value="{{ $value->display_value }}" maxlength="100" placeholder="{{ __('admin.product_options.display_value') }}" class="rounded-lg border-slate-300 text-sm">
        <div class="relative"><input name="color_code" value="{{ $value->color_code }}" maxlength="20" placeholder="#000000" class="w-full rounded-lg border-slate-300 pl-9 text-sm">@if($value->color_code)<span class="absolute left-3 top-3 h-4 w-4 rounded-full border border-slate-300" style="background-color: {{ $value->color_code }}"></span>@endif</div>
        <input name="sort_order" value="{{ $value->sort_order }}" type="number" min="0" class="rounded-lg border-slate-300 text-sm">
        <label class="flex items-center gap-1.5 text-xs font-semibold text-slate-600"><input type="hidden" name="status" value="0"><input type="checkbox" name="status" value="1" @checked($value->status) class="rounded border-slate-300 text-indigo-600">{{ __('admin.common.active') }}</label>
        <div class="flex flex-wrap items-center gap-1"><span data-save-status class="text-[11px] font-bold" role="status"></span><button class="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-700">{{ __('admin.common.save') }}</button><details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-bold text-slate-600">•••</summary><div class="absolute right-0 top-full z-10 mt-1 w-28 rounded-lg border bg-white p-1 shadow-xl"><button type="button" data-async-delete data-delete-url="{{ route('admin.product-option-values.destroy', $value) }}" data-delete-target="[data-option-value-row='{{ $value->id }}']" data-delete-type="option-value" data-option-id="{{ $value->product_option_id }}" data-option-value-id="{{ $value->id }}" data-delete-title="{{ __('admin.delete_modal.option_value_title') }}" data-delete-message="{{ __('admin.delete_modal.option_value_message', ['name' => $value->label()]) }}" data-delete-warning="{{ __('admin.delete_modal.option_value_warning') }}" class="w-full rounded-md px-2 py-2 text-left text-xs font-bold text-rose-700 hover:bg-rose-50">{{ __('admin.common.delete') }}</button></div></details></div>
    </form>
</div>
