<div data-variant-image-panel="{{ $variant->id }}" x-show="selected === @js((string) $variant->id)" x-cloak class="p-6">
    <div class="mb-5 flex items-center justify-between gap-3"><span data-variant-image-count="{{ $variant->id }}" class="text-sm font-bold text-slate-500">{{ $variant->variantImages->count() }}</span>
    <x-admin.modal id="upload-variant-images-{{ $variant->id }}" :title="__('admin.variant_images.upload')" size="max-w-4xl">
        <x-slot:trigger><button type="button" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">{{ __('admin.variant_images.upload') }}</button></x-slot:trigger>
        <form method="POST" action="{{ route('admin.product-variants.images.store', $variant) }}" enctype="multipart/form-data" data-async-create data-append-target="#edit-variant-image-gallery-{{ $variant->id }}" class="grid gap-4 md:grid-cols-2">@csrf
            <div data-async-errors class="hidden md:col-span-2 rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700"></div>
            <div class="md:col-span-2"><label class="text-sm font-semibold">{{ __('admin.variant_images.files') }} *</label><input name="images[]" type="file" accept="image/jpeg,image/png,image/webp" multiple required class="mt-2 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"></div>
            <input name="alt_text" maxlength="255" placeholder="{{ __('admin.variant_images.alt_text') }}" class="self-end rounded-xl border-slate-300 text-sm"><input name="sort_order" type="number" min="0" placeholder="{{ __('admin.variant_images.auto') }}" class="self-end rounded-xl border-slate-300 text-sm">
            <div class="flex items-center gap-5 md:col-span-2"><label class="flex items-center gap-2 text-sm font-semibold"><input type="hidden" name="status" value="0"><input name="status" type="checkbox" value="1" checked class="rounded border-slate-300 text-indigo-600">{{ __('admin.common.active') }}</label><label class="flex items-center gap-2 text-sm font-semibold"><input type="hidden" name="is_main" value="0"><input name="is_main" type="checkbox" value="1" class="rounded border-slate-300 text-indigo-600">{{ __('admin.variant_images.set_first_main') }}</label><button class="ml-auto rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">{{ __('admin.variant_images.upload') }}</button></div>
        </form>
    </x-admin.modal></div>
    <div id="edit-variant-image-gallery-{{ $variant->id }}" class="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">@if($variant->variantImages->isEmpty())<div data-empty-state class="col-span-full rounded-xl border border-dashed border-slate-300 px-6 py-10 text-center text-sm text-slate-500">{{ __('admin.variant_images.empty') }}</div>@endif @foreach($variant->variantImages as $image) @include('admin.variant-images._card', ['image' => $image, 'service' => $variantImageService]) @endforeach</div>
</div>
