<article data-variant-row="{{ $variant->id }}" class="rounded-2xl border border-slate-200 p-4">
    <form method="POST" action="{{ route('admin.product-variants.update', $variant) }}" data-async-save class="grid gap-3 md:grid-cols-2 xl:grid-cols-8">
        @csrf @method('PUT')
        @foreach ($activeOptions as $option)
            <div data-variant-row-selector="{{ $option->id }}"><label class="text-xs font-bold text-slate-500">{{ $option->label() }}</label><select data-option-select="{{ $option->id }}" name="option_values[{{ $option->id }}]" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">—</option>@foreach($option->values->where('status', true) as $value)<option value="{{ $value->id }}" @selected($variant->optionValues->contains('id', $value->id))>{{ $value->label() }}</option>@endforeach</select></div>
        @endforeach
        <div><label class="text-xs font-bold text-slate-500">SKU</label><input name="sku" value="{{ $variant->sku }}" required class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div><label class="text-xs font-bold text-slate-500">{{ __('admin.variant_combinations.custom_name') }}</label><input name="name" value="{{ $variant->name }}" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div><label class="text-xs font-bold text-slate-500">{{ __('admin.products.price') }}</label><input name="price" value="{{ $variant->price }}" type="number" min="0" step="0.01" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div><label class="text-xs font-bold text-slate-500">{{ __('admin.products.sale_price') }}</label><input name="sale_price" value="{{ $variant->sale_price }}" type="number" min="0" step="0.01" class="mt-1 block w-full rounded-lg border-slate-300 text-sm"></div>
        <div class="flex items-end"><label class="flex items-center gap-2 pb-2 text-sm font-semibold text-slate-700"><input type="hidden" name="status" value="0"><input name="status" type="checkbox" value="1" @checked($variant->status) class="h-5 w-5 rounded border-slate-300 text-indigo-600">{{ __('admin.common.active') }}</label></div>
        <div class="flex flex-wrap items-end gap-2"><span data-save-status class="pb-2 text-[11px] font-bold" role="status"></span><button class="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-bold text-indigo-700">{{ __('admin.common.save') }}</button><details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">{{ __('admin.product_tabs.more') }}</summary><div class="absolute right-0 top-full z-10 mt-1 w-36 rounded-lg border bg-white p-1 shadow-xl"><button type="button" data-async-delete data-delete-url="{{ route('admin.product-variants.destroy', $variant) }}" data-delete-target="[data-variant-row='{{ $variant->id }}']" data-delete-type="variant" data-variant-id="{{ $variant->id }}" data-delete-title="{{ __('admin.delete_modal.variant_title') }}" data-delete-message="{{ __('admin.delete_modal.variant_message', ['name' => $variant->name ?: $variant->sku]) }}" data-delete-warning="{{ __('admin.delete_modal.variant_warning') }}" class="w-full rounded-md px-2 py-2 text-left text-xs font-bold text-rose-700 hover:bg-rose-50">{{ __('admin.common.delete') }}</button></div></details></div>
    </form>
    <div class="mt-3 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3">@forelse($variant->optionValues as $value)<span class="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-bold text-indigo-700">@if($value->color_code)<span class="h-3 w-3 rounded-full border" style="background-color: {{ $value->color_code }}"></span>@endif{{ $value->option->label() }}: {{ $value->label() }}</span>@empty<span class="text-xs font-semibold text-amber-600">{{ __('admin.variant_combinations.legacy_variant') }}</span>@endforelse <span class="ml-auto text-xs font-semibold text-slate-500">{{ __('admin.variant_combinations.stock') }}: {{ $variant->inventoryStock?->availableQuantity() ?? 0 }}</span><button type="button" @click="activeTab = 'variant-images'; $dispatch('select-variant-images', { id: {{ $variant->id }} })" class="inline-flex items-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700">@if($mainVariantImage = $variant->variantImages->firstWhere('is_main', true))<img src="/storage/{{ $mainVariantImage->image_path }}" alt="" class="h-6 w-6 rounded object-cover">@endif{{ __('admin.variant_images.manage') }} (<span data-variant-image-count="{{ $variant->id }}">{{ $variant->variantImages->count() }}</span>)</button></div>
</article>
