@extends('layouts.admin')
@section('title', __('admin.inventory.adjust_title'))
@section('content')
    @if($errors->any())<div class="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{{ $errors->first() }}</div>@endif
    <div class="grid gap-6 xl:grid-cols-3">
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-bold text-slate-950">{{ $productService->name($stock->product) }}</h2><p class="mt-1 text-sm text-slate-500">{{ $inventoryService->variantName($stock) }} · {{ $inventoryService->sku($stock) }}</p><dl class="mt-6 grid grid-cols-3 gap-3 text-center"><div class="rounded-xl bg-slate-50 p-3"><dt class="text-xs text-slate-500">{{ __('admin.inventory.quantity') }}</dt><dd class="mt-1 text-xl font-black">{{ $stock->quantity }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-xs text-slate-500">{{ __('admin.inventory.reserved') }}</dt><dd class="mt-1 text-xl font-black">{{ $stock->reserved_quantity }}</dd></div><div class="rounded-xl bg-indigo-50 p-3"><dt class="text-xs text-indigo-600">{{ __('admin.inventory.available') }}</dt><dd class="mt-1 text-xl font-black text-indigo-700">{{ $stock->availableQuantity() }}</dd></div></dl></section>
        <form method="POST" action="{{ route('admin.inventory.update', $stock) }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2">@csrf<div class="grid gap-6 p-6 md:grid-cols-2"><div><label class="text-sm font-semibold text-slate-800">{{ __('admin.inventory.adjustment_type') }} *</label><select name="adjustment_type" class="mt-2 block w-full rounded-xl border-slate-300 text-sm" required><option value="increase" @selected(old('adjustment_type')==='increase')>{{ __('admin.inventory.increase') }}</option><option value="decrease" @selected(old('adjustment_type')==='decrease')>{{ __('admin.inventory.decrease') }}</option><option value="set" @selected(old('adjustment_type')==='set')>{{ __('admin.inventory.set') }}</option></select></div><div><label class="text-sm font-semibold text-slate-800">{{ __('admin.inventory.adjust_quantity') }} *</label><input name="quantity" type="number" min="0" value="{{ old('quantity', 0) }}" class="mt-2 block w-full rounded-xl border-slate-300 text-sm" required></div><div><label class="text-sm font-semibold text-slate-800">{{ __('admin.inventory.threshold') }} *</label><input name="low_stock_threshold" type="number" min="0" value="{{ old('low_stock_threshold', $stock->low_stock_threshold) }}" class="mt-2 block w-full rounded-xl border-slate-300 text-sm" required></div><div><label class="text-sm font-semibold text-slate-800">{{ __('admin.inventory.reason') }}</label><input name="reason" maxlength="255" value="{{ old('reason') }}" class="mt-2 block w-full rounded-xl border-slate-300 text-sm"></div><div class="md:col-span-2"><label class="text-sm font-semibold text-slate-800">{{ __('admin.inventory.note') }}</label><textarea name="note" rows="4" class="mt-2 block w-full rounded-xl border-slate-300 text-sm">{{ old('note') }}</textarea></div></div><div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50/70 px-6 py-4"><a href="{{ route('admin.inventory.index') }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">{{ __('admin.common.back') }}</a><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white">{{ __('admin.inventory.save_adjustment') }}</button></div></form>
    </div>
@endsection
