@extends('layouts.admin')
@section('title', __('admin.inventory.title'))
@section('content')
    @if (session('success'))<div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
    <form method="GET" class="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-3 xl:grid-cols-5">
        <input name="keyword" value="{{ $filters['keyword'] ?? '' }}" placeholder="{{ __('admin.inventory.search') }}" class="rounded-xl border-slate-300 text-sm">
        <select name="category_id" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.inventory.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)($filters['category_id'] ?? 0) === $category->id)>{{ $categoryService->name($category) }}</option>@endforeach</select>
        <select name="stock_status" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.inventory.all_statuses') }}</option><option value="in_stock" @selected(($filters['stock_status'] ?? '') === 'in_stock')>{{ __('admin.inventory.in_stock') }}</option><option value="low_stock" @selected(($filters['stock_status'] ?? '') === 'low_stock')>{{ __('admin.inventory.low_stock') }}</option><option value="out_of_stock" @selected(($filters['stock_status'] ?? '') === 'out_of_stock')>{{ __('admin.inventory.out_of_stock') }}</option></select>
        <select name="product_type" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.inventory.all_types') }}</option><option value="product" @selected(($filters['product_type'] ?? '') === 'product')>{{ __('admin.inventory.product_only') }}</option><option value="variant" @selected(($filters['product_type'] ?? '') === 'variant')>{{ __('admin.inventory.variant_only') }}</option></select>
        <div class="flex gap-2"><button class="flex-1 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">{{ __('admin.inventory.filter') }}</button><a href="{{ route('admin.inventory.index') }}" class="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-slate-600">{{ __('admin.inventory.reset') }}</a></div>
    </form>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200">
        <thead><tr class="text-left text-xs font-bold uppercase tracking-wider text-slate-500"><th class="px-4 py-4">{{ __('admin.inventory.product') }}</th><th class="px-4 py-4">{{ __('admin.inventory.variant') }}</th><th class="px-4 py-4">SKU</th><th class="px-4 py-4">{{ __('admin.inventory.category') }}</th><th class="px-4 py-4 text-right">{{ __('admin.inventory.quantity') }}</th><th class="px-4 py-4 text-right">{{ __('admin.inventory.reserved') }}</th><th class="px-4 py-4 text-right">{{ __('admin.inventory.available') }}</th><th class="px-4 py-4 text-right">{{ __('admin.inventory.threshold') }}</th><th class="px-4 py-4">{{ __('admin.inventory.status') }}</th><th class="px-4 py-4">{{ __('admin.inventory.updated_at') }}</th><th class="px-6 py-4 text-right">{{ __('admin.common.actions') }}</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse($stocks as $stock)@php($status = $stock->stockStatus())<tr class="hover:bg-slate-50"><td class="px-4 py-4 font-bold text-slate-900">{{ $productService->name($stock->product) }}</td><td class="px-4 py-4 text-sm text-slate-600">{{ $inventoryService->variantName($stock) }}</td><td class="px-4 py-4"><code class="text-xs font-bold text-slate-700">{{ $inventoryService->sku($stock) }}</code></td><td class="px-4 py-4 text-sm text-slate-600">{{ $categoryService->name($stock->product->category) }}</td><td class="px-4 py-4 text-right font-bold text-slate-900">{{ $stock->quantity }}</td><td class="px-4 py-4 text-right text-slate-600">{{ $stock->reserved_quantity }}</td><td class="px-4 py-4 text-right font-bold text-indigo-700">{{ $stock->availableQuantity() }}</td><td class="px-4 py-4 text-right text-slate-600">{{ $stock->low_stock_threshold }}</td><td class="px-4 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold','bg-emerald-50 text-emerald-700'=>$status==='in_stock','bg-amber-50 text-amber-700'=>$status==='low_stock','bg-rose-50 text-rose-700'=>$status==='out_of_stock'])>{{ __('admin.inventory.'.$status) }}</span></td><td class="whitespace-nowrap px-4 py-4 text-sm text-slate-500">{{ $stock->updated_at?->format('Y-m-d H:i') }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.inventory.adjust', $stock) }}" class="rounded-lg border border-indigo-200 px-3 py-1.5 text-xs font-bold text-indigo-700">{{ __('admin.inventory.adjust') }}</a><a href="{{ route('admin.inventory.logs', $stock) }}" class="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700">{{ __('admin.inventory.history') }}</a></div></td></tr>@empty<tr><td colspan="11" class="px-6 py-16 text-center text-sm text-slate-500">{{ __('admin.inventory.empty') }}</td></tr>@endforelse</tbody>
    </table></div>@if($stocks->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $stocks->links() }}</div>@endif</div>
@endsection
