@if ($errors->any())
    <div class="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><p class="font-bold">{{ __('admin.tax_rates.review') }}</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<form method="POST" action="{{ $action }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    @csrf @if ($method !== 'POST') @method($method) @endif
    <div class="border-b border-slate-200 bg-slate-50/70 px-6 py-5"><h2 class="font-bold text-slate-950">{{ __('admin.tax_rates.details') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('admin.tax_rates.details_desc') }}</p></div>
    @php($inputClass = 'mt-2 block w-full rounded-xl border-slate-300 px-3 py-2.5 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500')
    <div class="grid gap-6 p-6 md:grid-cols-2">
        <div><label for="tax_class_id" class="text-sm font-semibold text-slate-800">{{ __('admin.tax_rates.tax_class') }} *</label><select id="tax_class_id" name="tax_class_id" class="{{ $inputClass }}" required><option value="">{{ __('admin.tax_rates.choose_class') }}</option>@foreach ($taxClasses as $class)<option value="{{ $class->id }}" @selected((int) old('tax_class_id', $taxRate->tax_class_id) === $class->id)>{{ $class->name }} ({{ $class->code }})</option>@endforeach</select>@error('tax_class_id')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="rate" class="text-sm font-semibold text-slate-800">{{ __('admin.tax_rates.rate') }} *</label><div class="relative"><input id="rate" name="rate" type="number" min="0" max="100" step="0.0001" value="{{ old('rate', $taxRate->rate) }}" class="{{ $inputClass }} pr-10" required><span class="absolute bottom-2.5 right-3 text-sm text-slate-500">%</span></div>@error('rate')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="country_code" class="text-sm font-semibold text-slate-800">{{ __('admin.tax_rates.country_code') }}</label><input id="country_code" name="country_code" maxlength="10" value="{{ old('country_code', $taxRate->country_code) }}" class="{{ $inputClass }} uppercase" placeholder="VN">@error('country_code')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="region" class="text-sm font-semibold text-slate-800">{{ __('admin.tax_rates.region') }}</label><input id="region" name="region" maxlength="100" value="{{ old('region', $taxRate->region) }}" class="{{ $inputClass }}">@error('region')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="priority" class="text-sm font-semibold text-slate-800">{{ __('admin.tax_rates.priority') }} *</label><input id="priority" name="priority" type="number" min="0" value="{{ old('priority', $taxRate->priority ?? 1) }}" class="{{ $inputClass }}" required>@error('priority')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <label class="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-slate-200 p-4"><span><span class="block text-sm font-semibold text-slate-800">{{ __('admin.common.active') }}</span><span class="mt-1 block text-xs text-slate-500">{{ __('admin.tax_rates.active_desc') }}</span></span><input name="status" type="checkbox" value="1" class="mt-1 h-5 w-5 rounded border-slate-300 text-indigo-600" @checked(old('status', $taxRate->exists ? $taxRate->status : true))></label>
    </div>
    <div class="flex justify-end gap-3 border-t border-slate-200 bg-slate-50/70 px-6 py-4"><a href="{{ route('admin.tax-rates.index') }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">{{ __('admin.common.back') }}</a><button class="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-indigo-700">{{ $submitLabel }}</button></div>
</form>
