<section x-show="activeTab === 'inventory'" x-cloak data-product-tab="inventory" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-slate-50/70 px-6 py-5"><div><h2 class="font-bold text-slate-950">{{ __('admin.inventory.title') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('admin.inventory.initial_reason') }}</p></div><a href="{{ route('admin.inventory.index', ['keyword' => $product->sku]) }}" class="rounded-xl border border-indigo-200 bg-white px-4 py-2 text-sm font-bold text-indigo-700">{{ __('admin.inventory.view_all') }}</a></div>
    @if($inventoryStocks->isEmpty())
        <div class="p-10 text-center text-sm font-semibold text-slate-500">{{ __('admin.product_tabs.inventory_empty') }}</div>
    @else
        <div class="overflow-x-auto"><table class="w-full min-w-[860px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">SKU</th><th class="px-6 py-4">{{ __('admin.inventory.quantity') }}</th><th class="px-6 py-4">{{ __('admin.inventory.reserved') }}</th><th class="px-6 py-4">{{ __('admin.inventory.available') }}</th><th class="px-6 py-4">{{ __('admin.inventory.threshold') }}</th><th class="px-6 py-4">{{ __('admin.inventory.status') }}</th><th class="px-6 py-4 text-right">{{ __('admin.common.actions') }}</th></tr></thead><tbody id="inventory-stock-list" class="divide-y divide-slate-100">@foreach($inventoryStocks as $stock) @include('admin.products.partials.inventory-row', ['stock' => $stock]) @endforeach</tbody></table></div>
        <div class="border-t border-slate-200 bg-slate-50/50 p-6"><h3 class="mb-3 text-sm font-extrabold text-slate-900">{{ __('admin.inventory.recent_logs') }}</h3><ul id="inventory-recent-logs" class="space-y-2">@foreach($inventoryStocks->flatMap->inventoryLogs->sortByDesc('created_at')->take(5) as $log) @include('admin.products.partials.inventory-log', ['log' => $log]) @endforeach</ul></div>
    @endif
</section>
