@extends('layouts.admin')
@section('title', __('admin.products.title'))
@section('page-actions')<a href="{{ route('admin.products.create') }}" class="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-700">+ {{ __('admin.products.add') }}</a>@endsection
@section('content')
    @if (session('success'))<div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="mb-6 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{{ $errors->first() }}</div>@endif
    <form method="GET" class="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-3 xl:grid-cols-6">
        <input name="keyword" value="{{ $filters['keyword'] ?? '' }}" placeholder="{{ __('admin.products.search') }}" class="rounded-xl border-slate-300 text-sm">
        <select name="category_id" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.products.all_categories') }}</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((int) ($filters['category_id'] ?? 0) === $category->id)>{{ $categoryService->name($category) }}</option>@endforeach</select>
        <select name="status" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.products.all_statuses') }}</option><option value="1" @selected(($filters['status'] ?? '') === '1')>{{ __('admin.common.active') }}</option><option value="0" @selected(($filters['status'] ?? '') === '0')>{{ __('admin.common.inactive') }}</option></select>
        <select name="is_featured" class="rounded-xl border-slate-300 text-sm"><option value="">{{ __('admin.products.all_featured') }}</option><option value="1" @selected(($filters['is_featured'] ?? '') === '1')>{{ __('admin.products.featured') }}</option><option value="0" @selected(($filters['is_featured'] ?? '') === '0')>{{ __('admin.products.normal') }}</option></select>
        <select name="sort" class="rounded-xl border-slate-300 text-sm"><option value="newest">{{ __('admin.products.newest') }}</option><option value="price_asc" @selected(($filters['sort'] ?? '') === 'price_asc')>{{ __('admin.products.price_asc') }}</option><option value="price_desc" @selected(($filters['sort'] ?? '') === 'price_desc')>{{ __('admin.products.price_desc') }}</option></select>
        <div class="flex gap-2"><button class="flex-1 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">{{ __('admin.products.filter') }}</button><a href="{{ route('admin.products.index') }}" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm font-bold text-slate-600">{{ __('admin.products.reset') }}</a></div>
    </form>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200">
        <thead><tr class="text-left text-xs font-bold uppercase tracking-wider text-slate-500"><th class="px-4 py-4">ID</th><th class="px-4 py-4">{{ __('admin.products.sku') }}</th><th class="px-4 py-4">{{ __('admin.products.name') }}</th><th class="px-4 py-4">{{ __('admin.products.category') }}</th><th class="px-4 py-4">{{ __('admin.products.price') }}</th><th class="px-4 py-4">{{ __('admin.products.sale_price') }}</th><th class="px-4 py-4">{{ __('admin.common.active') }}</th><th class="px-4 py-4">{{ __('admin.products.featured') }}</th><th class="px-4 py-4">{{ __('admin.products.created_at') }}</th><th class="px-6 py-4 text-right">{{ __('admin.common.actions') }}</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse ($products as $product)<tr class="hover:bg-slate-50">
            <td class="px-4 py-4 text-sm text-slate-500">#{{ $product->id }}</td><td class="px-4 py-4"><code class="text-xs font-bold text-slate-700">{{ $product->sku }}</code></td>
            <td class="px-4 py-4"><p class="font-bold text-slate-900">{{ $productService->name($product) }}</p><p class="text-xs text-slate-500">{{ $product->productVariants->count() }} {{ __('admin.products.variants_short') }}</p></td>
            <td class="px-4 py-4 text-sm text-slate-600">{{ $categoryService->name($product->category) }}</td>
            <td class="whitespace-nowrap px-4 py-4 text-sm font-semibold text-slate-800">{{ $defaultCurrency ? $currencyService->format((float) $product->price, $defaultCurrency) : $product->price }}</td>
            <td class="whitespace-nowrap px-4 py-4 text-sm text-rose-600">{{ $product->sale_price !== null ? ($defaultCurrency ? $currencyService->format((float) $product->sale_price, $defaultCurrency) : $product->sale_price) : '—' }}</td>
            <td class="px-4 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold','bg-emerald-50 text-emerald-700'=>$product->status,'bg-slate-100 text-slate-500'=>!$product->status])>{{ $product->status ? __('admin.common.active') : __('admin.common.inactive') }}</span></td>
            <td class="px-4 py-4 text-sm">{{ $product->is_featured ? __('admin.products.yes') : __('admin.products.no') }}</td><td class="whitespace-nowrap px-4 py-4 text-sm text-slate-500">{{ $product->created_at->format('Y-m-d') }}</td>
            <td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.products.edit', $product) }}" class="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold text-slate-700">{{ __('admin.common.edit') }}</a><form method="POST" action="{{ route('admin.products.destroy', $product) }}" onsubmit="return confirm(@js(__('admin.products.delete_confirm')))" >@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-bold text-rose-700">{{ __('admin.common.delete') }}</button></form></div></td>
        </tr>@empty<tr><td colspan="10" class="px-6 py-16 text-center text-sm text-slate-500">{{ __('admin.products.empty') }}</td></tr>@endforelse</tbody>
    </table></div>@if($products->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $products->links() }}</div>@endif</div>
@endsection
