<form method="GET" action="{{ route('products.index') }}" class="space-y-7">
    <input type="hidden" name="language" value="{{ $currentLanguage->code }}"><input type="hidden" name="currency" value="{{ $currentCurrency->code }}">
    @if(!empty($filters['keyword']))<input type="hidden" name="keyword" value="{{ $filters['keyword'] }}">@endif
    @if(!empty($filters['sort']))<input type="hidden" name="sort" value="{{ $filters['sort'] }}">@endif
    <div id="categories">
        <div class="mb-4 flex items-center justify-between"><h2 class="font-extrabold text-slate-950">{{ __('storefront.categories') }}</h2><span class="text-xs font-bold text-slate-400">{{ $categories->count() }}</span></div>
        <div class="max-h-64 space-y-1 overflow-y-auto pr-2">
            <label class="flex cursor-pointer items-center justify-between rounded-xl px-3 py-2.5 text-sm transition hover:bg-slate-50"><span class="font-semibold text-slate-700">{{ __('storefront.all_categories') }}</span><input type="radio" name="category" value="" @checked(empty($filters['category'])) class="border-slate-300 text-indigo-600 focus:ring-indigo-500"></label>
            @foreach($categories as $category)@php($slug = $catalogService->categorySlug($category, $currentLanguage))<label class="flex cursor-pointer items-center justify-between rounded-xl px-3 py-2.5 text-sm transition hover:bg-slate-50"><span class="pr-3 text-slate-600">{{ $catalogService->categoryName($category, $currentLanguage) }}</span><input type="radio" name="category" value="{{ $slug }}" @checked(($filters['category'] ?? '') === $slug) class="border-slate-300 text-indigo-600 focus:ring-indigo-500"></label>@endforeach
        </div>
    </div>
    <div class="border-t border-slate-100 pt-6"><h2 class="mb-4 font-extrabold text-slate-950">{{ __('storefront.price_range') }}</h2><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-semibold text-slate-500">{{ __('storefront.min_price') }}</label><input name="min_price" type="number" min="0" step="1" value="{{ $filters['min_price'] ?? '' }}" placeholder="0" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></div><div><label class="text-xs font-semibold text-slate-500">{{ __('storefront.max_price') }}</label><input name="max_price" type="number" min="0" step="1" value="{{ $filters['max_price'] ?? '' }}" placeholder="∞" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></div></div><p class="mt-2 text-xs text-slate-400">{{ __('storefront.base_currency_hint', ['currency' => $baseCurrency->code]) }}</p></div>
    <div class="border-t border-slate-100 pt-6"><h2 class="mb-4 font-extrabold text-slate-950">{{ __('storefront.availability') }}</h2><select name="stock" class="w-full rounded-xl border-slate-200 text-sm"><option value="">{{ __('storefront.all_stock') }}</option><option value="in_stock" @selected(($filters['stock'] ?? '')==='in_stock')>{{ __('storefront.in_stock') }}</option><option value="low_stock" @selected(($filters['stock'] ?? '')==='low_stock')>{{ __('storefront.low_stock') }}</option><option value="out_of_stock" @selected(($filters['stock'] ?? '')==='out_of_stock')>{{ __('storefront.out_of_stock') }}</option></select></div>
    <div class="grid grid-cols-2 gap-3"><a href="{{ route('products.index', ['language'=>$currentLanguage->code,'currency'=>$currentCurrency->code]) }}" class="rounded-xl border border-slate-200 px-4 py-3 text-center text-sm font-bold text-slate-600 transition hover:bg-slate-50">{{ __('storefront.clear') }}</a><button class="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-slate-200 transition hover:bg-indigo-600">{{ __('storefront.apply') }}</button></div>
</form>
